--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/TPEimperialPE/Prisons
build-by-default: true
branches:
- main
projects:
  Prisons:
    icon: "icon.png"
    path: ""
    libs:
      - src: poggit/libasynql/libasynql
        version: ^3.3.0
...
