name: Prisons
version: 2.1.0
api: 4.0.0
author: TPE
main: TPE\Prisons\Prisons
depend:
  - EconomyAPI
  - PurePerms

permissions:
  prisons.*:
    default: op
    description: Allows access to all prison commands.
    children:
      prisons.rankup:
        default: true
        description: Allows user to use /rankup.
      prisons.prestige:
        default: true
        description: Allows players to use /prestige.
      prisons.nomine.bypass:
        default: op
        description: Allows players to mine/place blocks in areas that are not mine areas.  
     
