# Configuration file for Prisons by TPE.

# Version, do not change.

version: 1.2

# Enable usage of the prestige command by setting this to true, 
# if you wish to disable prestiging set it to false.
prestige: true

# Ranks for prisons, do not alter the lowercase letters, you can modify the rankName,
# rank price and added-permissions, set out the added-permissions as follows:
# added-permissions:
#  - "test.permission"
#  - "test2.permission"

ranks:
  a:
    price: 1000
    rankName: "A"
    added-permissions: []
    removed-permissions: []
  b:
    price: 2500
    rankName: "B"
    added-permissions: []
    removed-permissions: []
  c:
    price: 5000
    rankName: "C"
    added-permissions: []
    removed-permissions: []
  d:
    price: 10000
    rankName: "D"
    added-permissions: []
    removed-permissions: []
  e:
    price: 20000
    rankName: "E"
    added-permissions: []
    removed-permissions: []
  f:
    price: 50000
    rankName: "F"
    added-permissions: []
    removed-permissions: []
  g:
    price: 100000
    rankName: "G"
    added-permissions: []
    removed-permissions: []
  h:
    price: 175000
    rankName: "H"
    added-permissions: []
    removed-permissions: []
  i:
    price: 300000
    rankName: "I"
    added-permissions: []
    removed-permissions: []
  j:
    price: 450000
    rankName: "J"
    added-permissions: []
    removed-permissions: []
  k:
    price: 650000
    rankName: "K"
    added-permissions: []
    removed-permissions: []
  l:
    price: 900000
    rankName: "L"
    added-permissions: []
    removed-permissions: []
  m:
    price: 1200000
    rankName: "M"
    added-permissions: []
    removed-permissions: []
  n:
    price: 1550000
    rankName: "N"
    added-permissions: []
    removed-permissions: []
  o:
    price: 1900000
    rankName: "O"
    added-permissions: []
    removed-permissions: []
  p:
    price: 2500000
    rankName: "P"
    added-permissions: []
    removed-permissions: []
  q:
    price: 3150000
    rankName: "Q"
    added-permissions: []
    removed-permissions: []
  r:
    price: 3700000
    rankName: "R"
    added-permissions: []
    removed-permissions: []
  s:
    price: 4400000
    rankName: "S"
    added-permissions: []
    removed-permissions: []
  t:
    price: 5150000
    rankName: "T"
    added-permissions: []
    removed-permissions: []
  u:
    price: 5900000
    rankName: "U"
    added-permissions: []
    removed-permissions: []
  v:
    price: 6900000
    rankName: "V"
    added-permissions: []
    removed-permissions: []
  w:
    price: 7000000
    rankName: "W"
    added-permissions: []
    removed-permissions: []
  x:
    price: 8200000
    rankName: "X"
    added-permissions: []
    removed-permissions: []
  y:
    price: 9300000
    rankName: "Y"
    added-permissions: []
    removed-permissions: []
  z:
    price: 11000000
    rankName: "Z"
    added-permissions: []
    removed-permissions: []

# Prestiging resets the prison rank of a player, the rank up prices are then multiplied by the following number:

prestige-multiplier: 1.25

# Name the world players are teleported to after ascending, leave empty for default world.

world-name: ""

# The name of the worlds plots are in, this is so players can actually place and break blocks in the plot world
# If you don't have a plot world then just put anything.

plot-world: "plots"

# Message sent to player if they attempt to mine but are not in plot world or are in a mine or have a specific permission
no-placing-here: "§cYou can not place blocks here!"

# Message sent to player if they attempt to place blocks but are not in plot world, in a mine or have a specific permission.
no-breaking-here: "§cYou can not break blocks here!"

# Set out removed-permissions in the same way as added-permissions.

# Regardless of what 'price' is, if the player has enough their money is reset to 0 to avoid exploits.

prestiges:
  1:
    price: 15000000
    added-permissions: []
    removed-permissions: []
  2:
    price: 25000000
    added-permissions: []
    removed-permissions: []
  3:
    price: 50000000
    added-permissions: []
    removed-permissions: []
    
no-perms: "§cYou do not have permission to use that command!"

max-rank: "§cYou are at the max rank, please prestige!"

ranked-up: "§aSuccessfully ranked up to §b{RANK}§a!"

not-enough-money-rankup: "§aYou require §b${NEEDED} §ain order to rank up!"

not-rank-z: "§cYou must be rank Z in order to prestige, you are rank §b{RANK}§c!"

max-prestige-level: "§cYou are already at the max prestige level!"

successfully-prestiged: "§aSuccessfully prestiged to prestige level §b{PRESTIGE}§a!"

not-enough-money-prestige: "§cYou require §b${NEEDED} §ain order to prestige to the next prestige level!"
